### PR TITLE
Get ready for fastboot 1.0

### PR DESCRIPTION
**Pull request by rwwagner90**

### CODE REVIEW

**Comment by rwwagner90** [comment]
@mhretab any chance we could get this merged and released please? If you want to add me as a collaborator on GitHub and npm I can merge and release myself, if you'd like. I would also be happy to move this to my organization Ship Shape, and maintain it there with you, if you would like to not have to worry about maintaining it by yourself.

**Comment by mhretab** [comment]
@rwwagner90 thanks for your help on maintaining this repo. I have made you a collaborator. About moving it to your organization, I actually want keep it here for now as I plan maintaining it in future.

**Comment by rwwagner90** [comment]
@mhretab No problem. Could you make me a collaborator on npm as well please, so I can do releases?

**Comment by mhretab** [comment]
rwwagner90 sure, is your npm username same as github?

**Comment by rwwagner90** [comment]
Thanks!

**Pull request merged**
