### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by rwwagner90** [comment]
Hi @bekzod, just curious, why the change here?

**Comment by bekzod** [comment]
since `imageCropper` is class/factory it should start with capital letter, no ? and for function just es6 format @rwwagner90

**Comment by rwwagner90** [comment]
@bekzod I'm not sure. It wouldn't be my call. It's just a `default` export right? So you could name it anything you want. Function shorthand is good for sure though 👍

**Comment by ncoden** [comment]
> So you could name it anything you want.

True, but it's always better to reuse/promote best practices in examples and documentations.

**Review by RobbieTheWagner — APPROVED** [review]

**Pull request merged**
